services:
  - type: web
    name: contactflow-frontend
    env: static
    rootDir: frontend
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
